### ISSUE TITLE
Body parameter validation doesn't match swagger specification

### ISSUE THREAD

**Issue by gdelafosse** [fleekjs/fleek-validator#26]
According to swagger specification http://swagger.io/specification/#parameterObject, the body parameter must be validated using a schema. This is not implemented this way in lib/validate/ctx.js.
Do I misinterpret the specification or is there a plan to support this later?

**Comment by johnhof** [comment]
My interpretation of the docs is that the schema is only used to define model submissions, rather than single parameters. We currently only support flat objects, but nested/model bodies should be supported soon.

Example model body (unsupported):
```javascript
{
  "user": {
    "name": "johnhof"
  }
}
```
 Example single body (supported):
```javascript
{
  "user_name": "johnhof
}
```

**Comment by gdelafosse** [comment]
To me the body should be just : 

    {
       "name": "johnhof"
    }
That's the way I understand this sentence from the[ body parameter specification](http://swagger.io/specification/#parameterObject) : 

> The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only.

As a result the line lib/validate/ctx.js:44 is wrong in the context of the body parameter as there will be no element called "parameter.name" in the posted json object.
What do you think?

**Comment by johnhof** [comment]
ah interesting, I somehow missed this. We can make this change, but we will need to do some hacking to make it support both. I know it seems silly, but at least in our case, this change would break a lot of existing applications.

Maybe set it so that if only one param is present, with a nested schema, it would treat that schema as the base.  Thats pretty ugly, but a major version bump seems extreme.

any input @lan-nguyen91?

**Comment by avnersorek** [comment]
Any plans on fixing this ?
For me it makes input validation much harder - I have to repeat my schema over and over.

**Comment by avnersorek** [comment]
FYI I'm getting around this by making the 'body' parameter not required and using this -
```
const swaggerValidate = require('swagger-validate');
function* validateSwaggerSchema(next) {
  const parameters = _.get(this, ['fleek', 'routeConfig', 'details', 'parameters']);
  const bodyParam = _.find(parameters, { name: 'body', in: 'body' });
  let error;

  if (bodyParam && bodyParam.schema) {
    error = swaggerValidate.model(this.request.body, bodyParam.schema);
  }

  if (error) {
    this.status = 400;
    this.response.body = error;
  }
  else yield next;
}

fleekRouter(app, {
  swagger: './swagger.json',
  validate: true,
  middleware: [ validateSwaggerSchema ]
});
```

**Comment by johnhof** [comment]
@avnersorek I'm working through some refactoring, but I haven't been able to commit much time to it lately. I will address the problem, but I cant really give a timeline right now. Sorry I dont have a better answer :/

**Comment by johnhof** [comment]
fixed in the new version
