### ISSUE TITLE
Does not handle zero

### ISSUE THREAD

**Issue by raymondbutcher** [fleekjs/fleek-validator#37]
Hi,

The code for handling default/required parameters is doing a truthiness test on the value.

https://github.com/fleekjs/fleek-validator/blob/v0.6.0/lib/validate/one.js#L41

This means that it returns an error when I use a value of `0` for the parameter `{type: 'integer', required: true}`

This also applies to `minimum: 0` and other things to do with numbers.

**Comment by johnhof** [comment]
Ah thank for the heads up @raymondbutcher  I'm  hoping to make updates to the framework this weekend, so i can hopefully fix it soon
